In [2]:
import numpy as np

# Arrays with the same shape
arr1 = np.array([[1, 2,3, 4]])
arr2 = np.array([[5, 6,7,8]])
print(arr1.shape)
# Repeat arr2 to have the same shape as arr1
arr2_repeated = arr2

# Concatenate
result_concatenate = np.concatenate((arr1, arr2_repeated), axis=1)
print("Concatenate Result:")
print(result_concatenate)
print(result_concatenate.shape)

# Stack
result_stack = np.stack((arr1, arr2_repeated), axis=0)
print("\nStack Result:")
print(result_stack)
print(result_stack.shape)


(1, 4)
Concatenate Result:
[[1 2 3 4 5 6 7 8]]
(1, 8)

Stack Result:
[[[1 2 3 4]]

 [[5 6 7 8]]]
(2, 1, 4)


In [3]:
arr1 = np.array([1, 2,3, 4])
arr1[2:]

array([3, 4])

In [10]:
import torch
print("1") if torch.cuda.is_available() else None
    # model.cuda()